apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-privileged
  name: hello-privileged
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-privileged
  template:
    metadata:
      labels:
        app: hello-privileged
    spec:
      containers:
      - image: andifalk/hello-root:latest-amd64
        name: hello-privileged
        securityContext:
          privileged: true
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      restartPolicy: Always
